package com.eactive.resourcehub.audit.entity;

public enum AuditActionType {
    VIEW,
    PREVIEW,
    DOWNLOAD,
    UPLOAD,
    UPDATE,
    UPDATE_DOCUMENT,
    DELETE,
    PERMISSION_CHANGE,
    APPROVE,
    REJECT,
    CREATE,
    CHANGE_ROLE,
    GRANT_PERMISSION,
    REVOKE_PERMISSION,
    REGENERATE_THUMBNAIL,
    SUBMIT_REVIEW,
    APPROVE_DOCUMENT,
    REJECT_DOCUMENT,
    DELETE_DOCUMENT,
    UPLOAD_RESUME_TEMPLATE,
    DOWNLOAD_RESUME_TEMPLATE
}
